### PR TITLE
Adds AppIcon.appiconset to `Sources/Theme/Assets.xcassets`

### PR DESCRIPTION
**Pull request by simonmitchell**
Fixes the framework not compiling using Carthage in Xcode 13.1

### CODE REVIEW

**Comment by BenShutt** [comment]
@simonmitchell Does this need to go into `release/v3.0.0`?

**Review by BenShutt — APPROVED** [review]

**Comment by simonmitchell** [comment]
@BenShutt I thought release/v3.0.0 had already been merged? :)

**Comment by BenShutt** [comment]
@simonmitchell It has yeah, but the branch is still there (for now) in case apps are referencing it. 

So it's fine to merge this but we might need to update release/v3.0.0 with this fix too if we want those apps to get the fix. Or just point at `develop` in the referencing app I guess (though pointing at release branches seems a bit safer)

**Comment by simonmitchell** [comment]
I guess as it's not a breaking change (or even a change that could introduce bugs) that's fine, I'd only be worried if we were doing breaking changes or changes that were big enough to include bugs into a release that's already being pointed at by apps.

**Pull request merged**
